apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestionentreprise-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gestionentreprise-backend
  template:
    metadata:
      labels:
        app: gestionentreprise-backend
    spec:
      # public sur Docker Hub -> imagePullSecrets pas obligatoire.
      containers:
        - name: app
          image: docker.io/adelbettaieb/gestionentreprise:latest
          ports:
            - containerPort: 8080
          # dé-commente si tu as des variables env (DB, etc.)
          # env:
          #   - name: SPRING_DATASOURCE_URL
          #     value: jdbc:mysql://mysql:3306/...
---
apiVersion: v1
kind: Service
metadata:
  name: gestionentreprise-svc
  namespace: default
spec:
  selector:
    app: gestionentreprise-backend
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
