# ---------------------------
# Deployment
# ---------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestionentreprise
  namespace: jenkins
  labels:
    app: gestionentreprise
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate                 # évite d’attendre l’extinction de l’ancien pod
  selector:
    matchLabels:
      app: gestionentreprise
  template:
    metadata:
      labels:
        app: gestionentreprise
    spec:
      terminationGracePeriodSeconds: 20
      containers:
        - name: app
          image: docker.io/adelbettaieb/gestionentreprise:latest
          imagePullPolicy: Always   # force le pull de :latest à chaque déploiement
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: ""
          # Probes basées sur le port TCP (sûr si pas d'endpoint /health)
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 12
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6
          # (optionnel) alloue un peu de ressources pour éviter l'éviction
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---
# ---------------------------
# Service
# ---------------------------
apiVersion: v1
kind: Service
metadata:
  name: gestionentreprise
  namespace: jenkins
  labels:
    app: gestionentreprise
spec:
  selector:
    app: gestionentreprise
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP

---
# ---------------------------
# Ingress (NGINX)
# ---------------------------
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gestionentreprise
  namespace: jenkins
spec:
  ingressClassName: nginx
  rules:
    - host: app.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gestionentreprise
                port:
                  number: 80
