apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestionentreprise
  namespace: jenkins
  labels:
    app: gestionentreprise
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: gestionentreprise
  template:
    metadata:
      labels:
        app: gestionentreprise
    spec:
      containers:
        - name: app
          image: docker.io/adelbettaieb/gestionentreprise:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: ""
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 12
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6
---
apiVersion: v1
kind: Service
metadata:
  name: gestionentreprise
  namespace: jenkins
  labels:
    app: gestionentreprise
spec:
  selector:
    app: gestionentreprise
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gestionentreprise
  namespace: jenkins
spec:
  ingressClassName: nginx
  rules:
    - host: app.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gestionentreprise
                port:
                  number: 80
