apiVersion: v1
kind: Service
metadata:
  name: gestionentreprise
  labels: { app: gestionentreprise }
spec:
  selector: { app: gestionentreprise }
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 32081
  type: NodePort
