apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gestionentreprise
  namespace: jenkins              # même ns que ton Service backend
  labels:
    release: kps                  # IMPORTANT: correspond au release Helm de kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames: ["jenkins"]       # on cible des Services dans le ns jenkins
  selector:
    matchLabels:
      app: gestionentreprise      # doit matcher labels du Service
  endpoints:
    - port: http                  # doit matcher le port *name* du Service (tu as name: http)
      path: /actuator/prometheus
      interval: 15s
